-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 15:17:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CUENTA_BANCARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA_BANCARIA` (
  `id_cuenta_bancaria` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_cuenta_bancaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLAN_CARRERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLAN_CARRERA` (
  `id_plan_carrera` INT NOT NULL AUTO_INCREMENT,
  `objetivo` VARCHAR(100) NOT NULL,
  `etapas` VARCHAR(100) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_plan_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTAMENTO` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta_bancaria` INT NOT NULL,
  `id_plan_carrera` INT NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(110) NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_contratacion` DATE NULL,
  `historial_laboral` VARCHAR(250) NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_cuenta_idx` (`id_cuenta_bancaria` ASC) VISIBLE,
  INDEX `id_plan_carrera_idx` (`id_plan_carrera` ASC) VISIBLE,
  INDEX `id_departamento_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `id_cuenta_bancaria`
    FOREIGN KEY (`id_cuenta_bancaria`)
    REFERENCES `mydb`.`CUENTA_BANCARIA` (`id_cuenta_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_plan_carrera`
    FOREIGN KEY (`id_plan_carrera`)
    REFERENCES `mydb`.`PLAN_CARRERA` (`id_plan_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVALUACION` (
  `id_evaluacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_evaluacion` DATE NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `resultado` DECIMAL(10,2) NOT NULL,
  `observaciones` VARCHAR(500) NULL,
  PRIMARY KEY (`id_evaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAPACITACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAPACITACION` (
  `id_capacitacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_capacitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-CAPACITACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-CAPACITACION` (
  `id_empleado-capacitacion` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_capacitacion` INT NOT NULL,
  `resultado` DECIMAL(10,2) NOT NULL,
  `comentarios` VARCHAR(250) NULL,
  PRIMARY KEY (`id_empleado-capacitacion`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_capacitacion_idx` (`id_capacitacion` ASC) VISIBLE,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_capacitacion`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `mydb`.`CAPACITACION` (`id_capacitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOMINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOMINA` (
  `id_nomina` INT NOT NULL AUTO_INCREMENT,
  `salario_base` DECIMAL(10,2) NOT NULL,
  `deducciones` DECIMAL(10,2) NOT NULL,
  `percepciones` DECIMAL(10,2) NOT NULL,
  `total_pagar` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_nomina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUSENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUSENCIA` (
  `id_ausencia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `motivo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_ausencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESUPUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESUPUESTO` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `periodo` DATE NOT NULL,
  `monto_asignado` DECIMAL(10,2) NOT NULL,
  `monto_utilizado` DECIMAL(10,2) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_presupuesto`),
  INDEX `id_departamento_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_presupuesto_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTO` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-PROYECTO` (
  `id_empleado-proyecto` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  `horas_asignadas` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  PRIMARY KEY (`id_empleado-proyecto`),
  INDEX `id_proyecto_idx` (`id_proyecto` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_proyecto`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`PROYECTO` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CENTRO_COSTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CENTRO_COSTO` (
  `id_centro_costo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descipcion` VARCHAR(100) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_centro_costo`),
  INDEX `fk_CENTRO_COSTO_DEPARTAMENTO1_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_id_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUENTA_CONTABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA_CONTABLE` (
  `id_cuenta_contable` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `id_centro_costo` INT NOT NULL,
  PRIMARY KEY (`id_cuenta_contable`),
  INDEX `id_centro_costo_idx` (`id_centro_costo` ASC) VISIBLE,
  CONSTRAINT `fk_id_centro_costo`
    FOREIGN KEY (`id_centro_costo`)
    REFERENCES `mydb`.`CENTRO_COSTO` (`id_centro_costo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MOVIMIENTO_FINANCIERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MOVIMIENTO_FINANCIERO` (
  `id_movimiento_financiero` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta_contable` INT NOT NULL,
  `fecha_hora_movimiento` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `descripcion` VARCHAR(145) NULL,
  `id_cuenta_bancaria` INT NOT NULL,
  `tipo_cuenta` BINARY NOT NULL,
  PRIMARY KEY (`id_movimiento_financiero`),
  INDEX `id_cuenta_contable_idx` (`id_cuenta_contable` ASC) VISIBLE,
  INDEX `fk_MOVIMIENTO_FINANCIERO_CUENTA_BANCARIA1_idx` (`id_cuenta_bancaria` ASC) VISIBLE,
  CONSTRAINT `fk_id_cuenta_contable`
    FOREIGN KEY (`id_cuenta_contable`)
    REFERENCES `mydb`.`CUENTA_CONTABLE` (`id_cuenta_contable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIMIENTO_FINANCIERO_CUENTA_BANCARIA1`
    FOREIGN KEY (`id_cuenta_bancaria`)
    REFERENCES `mydb`.`CUENTA_BANCARIA` (`id_cuenta_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BENFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BENFICIO` (
  `id_beneficio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_beneficio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-BENEFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-BENEFICIO` (
  `id_empleado_beneficio` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_beneficio` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  PRIMARY KEY (`id_empleado_beneficio`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_beneficio_idx` (`id_beneficio` ASC) VISIBLE,
  CONSTRAINT `fkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_beneficio`
    FOREIGN KEY (`id_beneficio`)
    REFERENCES `mydb`.`BENFICIO` (`id_beneficio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-AUSENECIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-AUSENECIA` (
  `id_empleado-ausencia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_ausencia` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-ausencia`),
  INDEX `id_ausencia_idx` (`id_ausencia` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `forkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ausencia`
    FOREIGN KEY (`id_ausencia`)
    REFERENCES `mydb`.`AUSENCIA` (`id_ausencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-NOMINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-NOMINA` (
  `id_empleado-nomina` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_nomina` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-nomina`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_nomina_idx` (`id_nomina` ASC) VISIBLE,
  CONSTRAINT `foreignk_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_nomina`
    FOREIGN KEY (`id_nomina`)
    REFERENCES `mydb`.`NOMINA` (`id_nomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-EVALUACION` (
  `id_empleado-evaluacion` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_evaluacion` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-evaluacion`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_evaluacion_idx` (`id_evaluacion` ASC) VISIBLE,
  CONSTRAINT `foreignkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_evaluacion`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `mydb`.`EVALUACION` (`id_evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
