-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 15:17:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CUENTA_BANCARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA_BANCARIA` (
  `id_cuenta_bancaria` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_cuenta_bancaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLAN_CARRERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLAN_CARRERA` (
  `id_plan_carrera` INT NOT NULL AUTO_INCREMENT,
  `objetivo` VARCHAR(100) NOT NULL,
  `etapas` VARCHAR(100) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_plan_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPARTAMENTO` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta_bancaria` INT NOT NULL,
  `id_plan_carrera` INT NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(110) NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_contratacion` DATE NULL,
  `historial_laboral` VARCHAR(250) NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_cuenta_idx` (`id_cuenta_bancaria` ASC) VISIBLE,
  INDEX `id_plan_carrera_idx` (`id_plan_carrera` ASC) VISIBLE,
  INDEX `id_departamento_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `id_cuenta_bancaria`
    FOREIGN KEY (`id_cuenta_bancaria`)
    REFERENCES `mydb`.`CUENTA_BANCARIA` (`id_cuenta_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_plan_carrera`
    FOREIGN KEY (`id_plan_carrera`)
    REFERENCES `mydb`.`PLAN_CARRERA` (`id_plan_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVALUACION` (
  `id_evaluacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_evaluacion` DATE NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `resultado` DECIMAL(10,2) NOT NULL,
  `observaciones` VARCHAR(500) NULL,
  PRIMARY KEY (`id_evaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAPACITACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAPACITACION` (
  `id_capacitacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_capacitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-CAPACITACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-CAPACITACION` (
  `id_empleado-capacitacion` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_capacitacion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `resultado` DECIMAL(10,2) NOT NULL,
  `comentarios` VARCHAR(250) NULL,
  PRIMARY KEY (`id_empleado-capacitacion`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_capacitacion_idx` (`id_capacitacion` ASC) VISIBLE,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_capacitacion`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `mydb`.`CAPACITACION` (`id_capacitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOMINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOMINA` (
  `id_nomina` INT NOT NULL AUTO_INCREMENT,
  `salario_base` DECIMAL(10,2) NOT NULL,
  `deducciones` DECIMAL(10,2) NOT NULL,
  `percepciones` DECIMAL(10,2) NOT NULL,
  `total_pagar` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_nomina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUSENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUSENCIA` (
  `id_ausencia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `motivo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_ausencia`),
  CONSTRAINT `fk_ausencia_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ASISTENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASISTENCIA` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  CONSTRAINT `fk_asistencia_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRESUPUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRESUPUESTO` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `periodo` DATE NOT NULL,
  `monto_asignado` DECIMAL(10,2) NOT NULL,
  `monto_utilizado` DECIMAL(10,2) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_presupuesto`),
  INDEX `id_departamento_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_presupuesto_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTO` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-PROYECTO` (
  `id_empleado-proyecto` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  `horas_asignadas` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  PRIMARY KEY (`id_empleado-proyecto`),
  INDEX `id_proyecto_idx` (`id_proyecto` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_proyecto`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`PROYECTO` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CENTRO_COSTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CENTRO_COSTO` (
  `id_centro_costo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descipcion` VARCHAR(100) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_centro_costo`),
  INDEX `fk_CENTRO_COSTO_DEPARTAMENTO1_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_id_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`DEPARTAMENTO` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CUENTA_CONTABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUENTA_CONTABLE` (
  `id_cuenta_contable` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `id_centro_costo` INT NOT NULL,
  PRIMARY KEY (`id_cuenta_contable`),
  INDEX `id_centro_costo_idx` (`id_centro_costo` ASC) VISIBLE,
  CONSTRAINT `fk_id_centro_costo`
    FOREIGN KEY (`id_centro_costo`)
    REFERENCES `mydb`.`CENTRO_COSTO` (`id_centro_costo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MOVIMIENTO_FINANCIERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MOVIMIENTO_FINANCIERO` (
  `id_movimiento_financiero` INT NOT NULL AUTO_INCREMENT,
  `id_cuenta_contable` INT NOT NULL,
  `fecha_hora_movimiento` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `descripcion` VARCHAR(145) NULL,
  `id_cuenta_bancaria` INT NOT NULL,
  `tipo_cuenta` BINARY NOT NULL,
  PRIMARY KEY (`id_movimiento_financiero`),
  INDEX `id_cuenta_contable_idx` (`id_cuenta_contable` ASC) VISIBLE,
  INDEX `fk_MOVIMIENTO_FINANCIERO_CUENTA_BANCARIA1_idx` (`id_cuenta_bancaria` ASC) VISIBLE,
  CONSTRAINT `fk_id_cuenta_contable`
    FOREIGN KEY (`id_cuenta_contable`)
    REFERENCES `mydb`.`CUENTA_CONTABLE` (`id_cuenta_contable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIMIENTO_FINANCIERO_CUENTA_BANCARIA1`
    FOREIGN KEY (`id_cuenta_bancaria`)
    REFERENCES `mydb`.`CUENTA_BANCARIA` (`id_cuenta_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BENFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BENEFICIO` (
  `id_beneficio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(145) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_beneficio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-BENEFICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-BENEFICIO` (
  `id_empleado_beneficio` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_beneficio` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  PRIMARY KEY (`id_empleado_beneficio`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_beneficio_idx` (`id_beneficio` ASC) VISIBLE,
  CONSTRAINT `fkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_beneficio`
    FOREIGN KEY (`id_beneficio`)
    REFERENCES `mydb`.`BENFICIO` (`id_beneficio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-AUSENECIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-AUSENCIA` (
  `id_empleado-ausencia` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_ausencia` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-ausencia`),
  INDEX `id_ausencia_idx` (`id_ausencia` ASC) VISIBLE,
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `forkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ausencia`
    FOREIGN KEY (`id_ausencia`)
    REFERENCES `mydb`.`AUSENCIA` (`id_ausencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-NOMINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-NOMINA` (
  `id_empleado-nomina` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_nomina` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-nomina`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_nomina_idx` (`id_nomina` ASC) VISIBLE,
  CONSTRAINT `foreignk_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_nomina`
    FOREIGN KEY (`id_nomina`)
    REFERENCES `mydb`.`NOMINA` (`id_nomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO-EVALUACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO-EVALUACION` (
  `id_empleado-evaluacion` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_evaluacion` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_empleado-evaluacion`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_evaluacion_idx` (`id_evaluacion` ASC) VISIBLE,
  CONSTRAINT `foreignkey_id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_evaluacion`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `mydb`.`EVALUACION` (`id_evaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Creación de la tabla USUARIO
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL UNIQUE, -- Usaremos el email como nombre de usuario
  `password_hash` VARCHAR(255) NOT NULL, -- Para almacenar el hash de la contraseña
  `rol` ENUM('administrador', 'finanzas', 'recursos_humanos', 'invitado') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

INSERT INTO USUARIO (email, password_hash, rol)
VALUES (
    'admin@gmail.com',
    'scrypt:32768:8:1$UfINWj8THZ1OAaNT$7c280cd5950f74c326b0e5ce7987b0e5dd65d5e8341a797360d836dc69463db515c92b7cc6c49bc36478e92487032a934c2409d7896b8a94d642e2df67fa723f',
    'administrador'
);


INSERT INTO `CUENTA_BANCARIA` (banco, numero_cuenta, saldo) VALUES
('BBVA', '0011223344', 15000.00),
('Santander', '5566778899', 23000.50),
('Banorte', '9988776655', 12000.75);

INSERT INTO `PLAN_CARRERA` (objetivo, etapas, fecha_inicio, fecha_fin) VALUES
('Desarrollador Senior', 'Junior-Mid-Senior', '2025-01-01', '2027-01-01'),
('Gerente de Proyectos', 'Analista-Lider-Gerente', '2024-05-01', '2026-05-01'),
('Especialista en Finanzas', 'Junior-Senior-Especialista', '2023-03-01', '2025-03-01');

INSERT INTO `DEPARTAMENTO` (nombre, descripcion) VALUES
('Sistemas', 'Departamento de TI y desarrollo'),
('Recursos Humanos', 'Manejo de personal'),
('Finanzas', 'Control financiero y presupuestos');

INSERT INTO `EMPLEADO`
(id_cuenta_bancaria, id_plan_carrera, nombre_completo, direccion, telefono, fecha_nacimiento, cargo, fecha_contratacion, historial_laboral, id_departamento)
VALUES
(1, 1, 'Juan Sauza', 'Calle Uno #123', '555 1001', '1990-05-10', 'Developer', '2024-02-15', '9 meses en soporte', 1),
(2, 2, 'Daniela Guerra', 'Calle Dos #456', '555 2002', '1985-11-20', 'HR Manager', '2023-12-01', '5 meses en manejo de personal', 2),
(3, 3, 'Carlos Herrera', 'Calle Tres #789', '555 3003', '1992-07-15', 'Analista Financiero', '2022-09-10', '7 meses como auxiliar contable', 3),
(1, 2, 'Ana Cruz', 'Calle Cuatro #321', '555 4004', '1988-03-25', 'Project Manager', '2024-01-20', '3 meses en manejo de proyectos', 1),
(2, 1, 'Luis Murillo', 'Calle Cinco #654', '555 5005', '1991-12-30', 'Software Engineer', '2023-11-15', '5 meses en desarrollo web', 1),
(3, 3, 'Brenda Amezola', 'Calle Seis #987', '555 6006', '1987-09-05', 'Financial Advisor', '2022-08-05', '6 meses como asesor financiero', 3);

INSERT INTO `EVALUACION` (fecha_evaluacion, tipo, resultado, observaciones) VALUES
('2024-06-01', 'Anual', 90.50, 'Excelente rendimiento'),
('2024-09-15', 'Semestral', 75.00, 'Cumplimiento adecuado'),
('2025-01-10', 'Especial', 88.00, 'Mejoras visibles');

INSERT INTO `CAPACITACION` (nombre, descripcion, fecha_inicio, fecha_fin, proveedor) VALUES
('Python Avanzado', 'Estructuras de datos', '2024-01-10', '2024-01-20', 'Coding Academy'),
('Liderazgo', 'Taller de habilidades gerenciales', '2023-05-01', '2023-05-05', 'HREdu'),
('Finanzas Avanzadas', 'Consultor financiero', '2024-03-15', '2024-03-30', 'FinancePro');

INSERT INTO `mydb`.`EMPLEADO-CAPACITACION`
(id_empleado, id_capacitacion, fecha_inicio, fecha_fin, resultado, comentarios)
VALUES
(1, 1, '2025-01-10', '2025-01-20', 88.50, 'Buen manejo de conceptos'),
(2, 3, '2025-02-01', '2025-02-15', 92.00, 'Excelente rendimiento'),
(3, 2, '2025-03-05', '2025-03-18', 75.25, 'Necesita reforzar algunos temas');

INSERT INTO `NOMINA` (salario_base, deducciones, percepciones, total_pagar) VALUES
(15000.00, 2000.00, 3000.00, 16000.00),
(18000.00, 2500.00, 3200.00, 18700.00),
(22000.00, 3000.00, 4000.00, 23000.00);

INSERT INTO `mydb`.`AUSENCIA` (`id_empleado`, `tipo`, `fecha_inicio`, `fecha_fin`, `motivo`) VALUES
(1, 'Enfermedad', '2024-10-01 09:00:00', '2024-10-03 18:00:00', 'Gripe'),
(2, 'Vacaciones', '2024-12-20 00:00:00', '2024-12-27 23:59:59', 'Vacaciones anuales'),
(3, 'Permiso', '2025-03-10 09:00:00', '2025-03-10 13:00:00', 'Cita con el doctor');

INSERT INTO `mydb`.`ASISTENCIA` (`id_empleado`, `fecha_inicio`, `fecha_fin`) VALUES
(1, '2025-01-02 08:30:00', '2025-01-02 17:30:00'),
(2, '2025-01-02 09:00:00', '2025-01-02 18:00:00'),
(3, '2025-01-02 08:45:00', '2025-01-02 17:15:00');

INSERT INTO `PRESUPUESTO` (periodo, monto_asignado, monto_utilizado, id_departamento) VALUES
('2024-01-01', 500000.00, 200000.00, 1),
('2024-01-01', 300000.00, 150000.00, 2),
('2024-01-01', 700000.00, 500000.00, 3);

INSERT INTO `PROYECTO` (nombre, descripcion, fecha_inicio, fecha_fin) VALUES
('Sistema Contable', 'Desarrollo de un sistema contable interno', '2024-01-01', '2024-06-30'),
('Portal RH', 'Plataforma web de recursos humanos', '2024-03-01', '2024-09-30'),
('App Financiera', 'App de celular para reportes financieros', '2024-05-15', '2024-11-15');

INSERT INTO `EMPLEADO-PROYECTO` (id_empleado, id_proyecto, horas_asignadas, fecha_asignacion, fecha_entrega) VALUES
(1, 1, 120, '2024-01-10', '2024-04-10'),
(2, 2, 90, '2024-02-01', '2024-03-15'),
(3, 3, 140, '2024-03-05', '2024-06-01');

INSERT INTO `CENTRO_COSTO` (nombre, descipcion, id_departamento) VALUES
('Infraestructura', 'Costos de hardware y redes', 1),
('Capacitación', 'Gastos de cursos', 2),
('Contabilidad', 'Gestión financiera', 3);

INSERT INTO `CUENTA_CONTABLE` (banco, numero_cuenta, tipo, saldo, id_centro_costo) VALUES
('BBVA', 'CC1111', 'Operativa', 50000.00, 1),
('Santander', 'CC2222', 'Invertir', 75000.00, 2),
('Banorte', 'CC3333', 'Ahorro', 60000.00, 3),
('HSBC', 'CC4444', 'Operativa', 82000.00, 1);

INSERT INTO `MOVIMIENTO_FINANCIERO`
(id_cuenta_contable, fecha_hora_movimiento, tipo, monto, descripcion, id_cuenta_bancaria, tipo_cuenta)
VALUES
(1, '2024-02-10 10:30:00', 'Cargo', 5000.00, 'Compra de equipos', 1, 1),
(2, '2024-03-05 14:00:00', 'Abono', 12000.00, 'Ingreso extra', 2, 1),
(3, '2024-04-01 09:45:00', 'Cargo', 3000.00, 'Pago de servicio', 3, 1);

INSERT INTO `BENEFICIO` (nombre, descripcion, tipo) VALUES
('Vales de despensa', 'Apoyo alimentario mensual', 'Monetario'),
('Seguro Médico', 'Cobertura de salud privada', 'Salud'),
('Bono por rendimiento', 'Recompensa por objetivos cumplidos', 'Bono');

INSERT INTO `EMPLEADO-BENEFICIO` (id_empleado, id_beneficio, fecha_asignacion) VALUES
(1, 1, '2024-02-01'),
(2, 2, '2024-02-10'),
(3, 3, '2024-03-01');

INSERT INTO `EMPLEADO-AUSENCIA` (id_empleado, id_ausencia, fecha_inicio, fecha_final) VALUES
(1, 1, '2024-02-01 09:00:00', '2024-02-03 18:00:00'),
(2, 2, '2024-07-10 08:00:00', '2024-07-20 20:00:00'),
(3, 3, '2024-04-05 10:00:00', '2024-04-06 18:00:00');

INSERT INTO `EMPLEADO-NOMINA` (id_empleado, id_nomina, fecha_inicio, fecha_fin) VALUES
(1, 1, '2024-02-01 00:00:00', '2024-02-28 23:59:59'),
(2, 2, '2024-02-01 00:00:00', '2024-02-28 23:59:59'),
(3, 3, '2024-02-01 00:00:00', '2024-02-28 23:59:59');

INSERT INTO `EMPLEADO-EVALUACION` (id_empleado, id_evaluacion, fecha_inicio, fecha_fin) VALUES
(1, 1, '2024-06-01 09:00:00', '2024-06-01 10:00:00'),
(2, 2, '2024-09-15 09:00:00', '2024-09-15 10:00:00'),
(3, 3, '2025-01-10 09:00:00', '2025-01-10 10:00:00');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;